// Generated by CoffeeScript 1.6.3
var Logger, Verbose, path, utils;

path = require("path");

utils = require("./utils");

Verbose = false;

module.exports = Logger = (function() {
  Logger.verbose = function(value) {
    if (value != null) {
      Verbose = !!value;
    }
    return Verbose;
  };

  function Logger(prefix, logDevice) {
    this.prefix = prefix;
    this.logDevice = logDevice != null ? logDevice : console;
  }

  Logger.prototype.log = function(message) {
    return this.logDevice.log("" + this.prefix + ": " + message);
  };

  Logger.prototype.vlog = function(message) {
    if (!Verbose) {
      return;
    }
    return this.log(message);
  };

  Logger.prototype.err = function(message) {
    this.log("error: " + message);
    throw Error(message);
  };

  Logger.prototype.newLogger = function(prefix) {
    return new Logger("" + this.prefix + ": " + prefix, this.logDevice);
  };

  return Logger;

})();
