// Generated by CoffeeScript 1.6.3
var fs, utils;

fs = require("fs");

utils = exports;

utils.trim = function(string) {
  return string.replace(/(^\s+)|(\s+$)/g, '');
};

utils.alignLeft = function(string, length) {
  while (string.length < length) {
    string = "" + string + " ";
  }
  return string;
};

utils.alignRight = function(string, length) {
  while (string.length < length) {
    string = " " + string;
  }
  return string;
};

utils.alignRight0 = function(string, length) {
  while (string.length < length) {
    string = "0" + string;
  }
  return string;
};

utils.replaceTilde = function(fileName) {
  var tilde;
  tilde = process.env["HOME"] || process.env["USERPROFILE"] || '.';
  return fileName.replace('~', tilde);
};
